[tool.poetry]
name = "thread-safe-storage"
version = "0.1.0"
description = ""
authors = ["David Degenstein <ddegenstein15@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
